zomboidjar = ../project-zomboid-mod-toolkit/decompiled/lib/zomboid.jar
zomboidjarsources = ../project-zomboid-mod-toolkit/decompiled/lib/zomboid-sources.jar
zomboidlua = ../project-zomboid-mod-toolkit/decompiled/lib/zdoc-lua-41.73.jar
zomboidmedia = D:/Games/SteamLibrary/steamapps/common/ProjectZomboid/media